### ISSUE TITLE
Add ability to delete an item from a wishlist

### ISSUE THREAD

**Issue by adit2998** [CSCI-GA-2820-FA22-003/wishlists#10]
**As a** user  
 **I need** a REST API to delete an item from the wishlist  
 **So that** I can have a standard way to read an item from the wishlist  
   
 ### Details and Assumptions
 * The url to read the wishlist item should be `DELETE /wishlists/{id}/items/{item_id}` and should return the item with id as `{item_id}`.
 * The REST API should return `204_NO_CONTENT`, if the item exists or not exist 
 * The REST API should return useful error messages for invalid/incomplete requests.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the wishlist service
 When I call `DELETE /wishlists/{item_id}`
 Then I should delete the item requested from the wishlist if the item exists, error message otherwise.
 ```

**Comment by myan9** [comment]
Hey @adit2998 , I think there's some error in `Details and Assumptions` section. The url of this API should be `DELETE /wishlists/{id}/items/{id}`. Also, the professor mentioned in the lecture that it should be successful to delete an non-existing item.

Let me know if you think otherwise. @ashaychangwani @rsaim @hardy30894

**Comment by ashaychangwani** [comment]
> Also, the professor mentioned in the lecture that it should be successful to delete an non-existing item.

I don't remember this from the lecture, but if you're sure, that's good enough for me.

The Endpoint does need to be modified, since the current one should delete the entire wishlist.

**Comment by ashaychangwani** [comment]
>I need a REST API to read an item from the wishlist

I believe it should related to deleting a wishlist

**Comment by ashaychangwani** [comment]
> * The url to read the wishlist item should be DELETE /wishlists/{item_id} and should return the item with id as {item_id}.
> * The REST API should return 200_OK, if the item exists and can be read and returned and should return the details of the item requested.

Why are we returning the wishlist after deleting? Can't we just return 204_NO_CONTENT if the wishlist was successfully deleted?

**Comment by adit2998** [comment]
> > * The url to read the wishlist item should be DELETE /wishlists/{item_id} and should return the item with id as {item_id}.
> > * The REST API should return 200_OK, if the item exists and can be read and returned and should return the details of the item requested.
> 
> Why are we returning the wishlist after deleting? Can't we just return 204_NO_CONTENT if the wishlist was successfully deleted?

I think we should be returning the wishlist because this endpoint is deleting a specific item from the wishlist. So at the end of a successful deletion, the user can see their updated wishlist. Let me know what you guys think!

**Comment by adit2998** [comment]
> Hey @adit2998 , I think there's some error in `Details and Assumptions` section. The url of this API should be `DELETE /wishlists/{id}/items/{id}`. Also, the professor mentioned in the lecture that it should be successful to delete an non-existing item.
> 
> Let me know if you think otherwise. @ashaychangwani @rsaim @hardy30894

Yes you're right. Just modified the url.
