### ISSUE TITLE
Add query string support to List function as per wishlist name

### ISSUE THREAD

**Issue by rsaim** [CSCI-GA-2820-FA22-003/wishlists#119]
**As a** user 
 **I need** filter operation on my wishlists
 **So that** I can lookup my wishlists by name
   
 ### Details and Assumptions
• Query Resources by the wishlist `name`
• Add query capability to the model
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a GET call at /wishlist
 When I pass a query string like /wishlist?name=favorites
 Then wishlists containing the string "favorites" must be returned
 ```

**Comment by myan9** [comment]
Hey @rsaim, this is already covered by https://github.com/CSCI-GA-2820-FA22-003/wishlists/issues/51.
And you can try creating a couple of wishlists by name "yo", and search for "yo".
<img width="1542" alt="Screen Shot 2022-12-05 at 8 59 40 PM" src="https://user-images.githubusercontent.com/21212160/205820202-4786edad-b40c-4df9-b3b4-f3d50ff4489a.png">
