### ISSUE TITLE
Two UIs on homepage when running locally

### ISSUE THREAD

**Issue by rsaim** [CSCI-GA-2820-FA22-003/wishlists#124]
**Describe the bug**
I see 2 UIs when I run server locally in Docker

**To Reproduce**
1. Open the repo in container in VScode
2. Run `honcho start`
3. Go to homepage at http://localhost:8080/ in a browser

**Expected behavior**
Only 1 UI should be present

**Actual Behavior**
2 same UIs are present

**Additional context**
I don't see 2 UIs on the deployed services on IBM cloud.
dev - http://159.122.183.157:31001/
prod - http://159.122.183.157:31002/

<img width="1446" alt="image" src="https://user-images.githubusercontent.com/8366281/205538301-fc585edd-a694-4f6c-ae39-81e4ab520bcf.png">

**Comment by ashaychangwani** [comment]
This isn't a bug, this is because there are 2 forms required for the 2 different models we have (Wishlists and Items).

As such, we need forms to modify both of them.
