### ISSUE TITLE
Add ability to create a wishlist

### ISSUE THREAD

**Issue by rsaim** [CSCI-GA-2820-FA22-003/wishlists#15]
**As a** User
 **I need** the ability to create one or more wishlists
 **So that** I can save items to buy in future
   
 ### Details and Assumptions
 * We expect a POST at `/wishlist`
 * The response should contain the ID of the wishlist created
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given 
    POST call at `/wishlist`
 When
    The POST body contains the customer ID
 Then
    HTTP response HTTP 201 should be returned on success. 
    A JSON containing the ID of the wishlist created should be returned.
    ```
    {
     "wishlist_id": <id>,
    }
    ```
 Appropriate HTTP exceptions should be returned in other cases.
 ```

**Comment by myan9** [comment]
Should we refine the issue title to be "Add REST Endpoint to create a wishlist by name" to highlight that our service support adding multiple wishlists?

@rsaim @ashaychangwani @adit2998 @hardy30894

**Comment by rsaim** [comment]
> Should we refine the issue title to be "Add REST Endpoint to create a wishlist by name" to highlight that our service support adding multiple wishlists?
> 
> @rsaim @ashaychangwani @adit2998 @hardy30894

Done
