### ISSUE TITLE
Add ability to read a wishlist

### ISSUE THREAD

**Issue by rsaim** [CSCI-GA-2820-FA22-003/wishlists#16]
**As a** User
 **I need** to be able to read a wishlist
 **So that** I can interact with the wishlist
   
 ### Details and Assumptions
 * We assume the wishlist is already created
 * Return [404 Not Found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404) if the wishlist doesn't exist
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a GET call at `/wishlists/{id}`
 When I hit the end-point
 Then a JSON containing the items in the wishlist should be returned along with the name and ID of the wishlist.
{
  "wishlistName": <>,
  "wishlistID": <>,
  "num_items": <Number of items added in the wishlist>,
  "created_time": <>,
  "created_by": <>
}
Return 404 HTTP error if the wishlist doesn't exist.
 ```

**Comment by myan9** [comment]
Hey @rsaim, I think the API should be get a wishlist and return its metadata, e.g. created_time, created_by_user, wishlist_name, etc. Otherwise, your issue is duplicated with https://github.com/nyu-wishlist-squad/wishlists/issues/13 (list all items in a wishlist).

**Comment by ashaychangwani** [comment]
> We assume the wishlist is already created

Are we positive that we can assume the wishlist is already created? 

>Hey @rsaim, I think the API should get a wishlist and return its metadata, e.g. created_time, created_by_user, wishlist_name, etc. Otherwise, your issue is duplicated with https://github.com/nyu-wishlist-squad/wishlists/issues/13 (list all items in a wishlist).
Agreed

Can we also track access permissions of the wishlist? Otherwise a user could access someone else's wishlist which may not be ideal

**Comment by adit2998** [comment]
Yes, I think we can have a distinction between this endpoint and the one which lists all items. This one can include the metadata. Also, are we only dealing with a single wishlist per user or multiple ones?

**Comment by rsaim** [comment]
@ashaychangwani 
> Are we positive that we can assume the wishlist is already created?
Error, as mentioned, should be returned in that case.

>Can we also track access permissions of the wishlist? Otherwise a user could access someone else's wishlist which may not be ideal
I think we should. This needs another story though.

>Also, are we only dealing with a single wishlist per user or multiple ones?
A user can have multiple wishlists.

**Comment by ashaychangwani** [comment]
> Error, as mentioned, should be returned in that case.
> I think we should. This needs another story though.

In that case, can we change assumptions to: 

* The user has access to the wishlist, if it exists.
* If the wishlist exists, the REST API returns 200_OK along with the metadata for wishlist with identifier `id`.
* If the wishlist does not exist, the REST API returns 404_NOT_FOUND.
