### ISSUE TITLE
Add ability to update a wishlist

### ISSUE THREAD

**Issue by rsaim** [CSCI-GA-2820-FA22-003/wishlists#17]
**As a** User 
 **I need** ability to update my wishlist
 **So that** I can change the items I wish to buy
   
 ### Details and Assumptions
 * The wishlist already exists
 * Return HTTP 404 if the wishlist doesn't exist
 * PUT call should be used to update the wishlist
 * PUT call will contain the the ID of all the updated items in the body
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a PUT call at `/wishlist/{id}`
 When the call is made with the list of ID of items in message body
 Then the wishlist should drop the existing list of ID of items and replace it with the new one
Return HTTP 200 if the update succeeds.
Return appropriate HTTP error code otherwise.
 ```

**Comment by myan9** [comment]
Hey @rsaim, I think this API should only change the metadata of the wishlist itself, e.g. wishlist_name. Otherwise, it's duplicated with the API to update item in a wishlist.

**Comment by hardy30894** [comment]
I think it will be used to update any associated information with a given wishlist, be it a name or a list of items. The other API to update an item only updates an item with a given id in a wishlist. This API can change/replace the list of old items with new ones.
