### ISSUE TITLE
Add ability to read an item from a wishlist

### ISSUE THREAD

**Issue by hardy30894** [CSCI-GA-2820-FA22-003/wishlists#4]
**As a** user  
 **I need** a REST API to read an item from the wishlist  
 **So that** I can have a standard way to read an item from the wishlist  
   
 ### Details and Assumptions
 * The url to read the wishlist item should be `GET /wishlists/{id}/items/{id}` and should return the item with id as `{id}`.
 * The REST API should return `200_OK`, if the item exists and can be read and returned and should return the details of the item requested. 
 * The REST API should return `404_NOT_FOUND` code if the item doesn't exist and should display an appropriate message.
 * The REST API should return useful error messages for invalid/incomplete requests.
 * The REST API should not modify the item in the wishlists.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the wishlist service
 When I call `GET /wishlists/{id}/items/{id}`
 Then I should return the details of the item requested from the wishlist if the item exists, error message otherwise.
 ```

**Comment by ashaychangwani** [comment]
I think the URL has to be: `/wishlists/{id}/items/{id}`

**Comment by myan9** [comment]
> I think the URL has to be: `/wishlists/{id}/items/{id}`

agree

**Comment by hardy30894** [comment]
Agreed, made the changes accordingly
